name: linting, testing, building

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  install-dependencies:
    uses: ./.github/workflows/setup.yml

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Linting typescript
        run: npm run lint:ts

      - name: Linting scss
        run: npm run lint:scss

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Unit testing
        run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Build
        run: npm run build:prod
