name: Linting, Testing, Building

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  linting-testing-building:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

        if: always()
      - name: Linting TypeScript
        run: npm run lint:ts

        if: always()
      - name: Linting SCSS
        run: npm run lint:scss

        if: always()
      - name: Unit testing
        run: npm run test:unit

        if: always()
      - name: Build
        run: npm run build:prod
